### ISSUE TITLE
Github actions

### ISSUE THREAD

**Issue by xorapps** [xorapps/EasyJNI#3]
Create a github action flle that 

1. downloads the kotlin compiler
2. changes dir to the tests folder
3. Installs `make`
4. Runs `make` inside the tests folder

**Comment by harshit82** [comment]
Hey @xorapps, I am new to GitHub Actions and am looking for projects to contribute to.
Can I work on this?

**Comment by charleschege** [comment]
Yes go ahead

**Comment by harshit82** [comment]
Do you have a communication channel like slack or discord? I have a few questions.

**Comment by xorapps** [comment]
No, this is quite a small project for that

**Comment by xorapps** [comment]
You can ask a question here

**Comment by harshit82** [comment]
When do you want to run this?

> Create a github action flle that
> 
>     1. downloads the kotlin compiler
> 
>     2. changes dir to the tests folder
> 
>     3. Installs `make`
> 
>     4. Runs `make` inside the tests folder

**Comment by xorapps** [comment]
It's needed now since I have finished writing all the tests

**Comment by harshit82** [comment]
No, I mean a trigger, at what event do you want to run this, like when someone opens a new pr, etc.

**Comment by xorapps** [comment]
Sorry I misunderstood, LOL

WHen someone makes a pull request or when a new changes are pushed to branch

**Comment by harshit82** [comment]
Any specific platform you want to run this on?

Here are some offered by GitHub:
![image](https://user-images.githubusercontent.com/93983185/229128696-c2192a81-d2ec-430d-8304-6d238857df8e.png)

**Comment by xorapps** [comment]
Ubuntu 22.04

**Comment by harshit82** [comment]
Do you want it for any specific type of pull request or all kinds?

Here are the types:
![image](https://user-images.githubusercontent.com/93983185/229133670-5f04ad68-c062-4fc6-8e2a-d19c136ea6a7.png)

**Comment by xorapps** [comment]
What I want is simple
1. RUn if any changes are made to the branch
2. Run if a pull request is made
3. Run in more changes are made to the pull request
4. Os should be ubuntu 22.04

**Comment by harshit82** [comment]
Do you want it for any specific type of pull request or all kinds?

Here are the types:
![image](https://user-images.githubusercontent.com/93983185/229133670-5f04ad68-c062-4fc6-8e2a-d19c136ea6a7.png)

**Comment by xorapps** [comment]
all kinds

**Comment by harshit82** [comment]
How to run the make file?

**Comment by harshit82** [comment]
What is the kotlin compiler for?

**Comment by harshit82** [comment]
> How to run the make file?

Never mind figured that out

**Comment by harshit82** [comment]
The workflow is ready if you do not wish to make any changes.

**Comment by harshit82** [comment]
Should I send a pull request?

**Comment by charleschege** [comment]
Yes. Open a pr. You can reference it here

**Comment by xorapps** [comment]
Yes send a pull request

**Comment by harshit82** [comment]
PR sent
